version: "3.9"

services:
    api:
        container_name: ai_agent
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/src/app
        env_file: .env
        environment:
            - API_PORT=$API_PORT
        ports:
            - $API_PORT:$API_PORT
        expose:
            - $API_PORT
        stdin_open: true
        tty: true
